### ISSUE TITLE
Can't Use New Spigot 1.8 Build System

### ISSUE THREAD

**Issue by Techcable** [ProjectTestificate/MinecraftMappings#1]
The MinecraftMappings scripts can't generate mappings for the new system.
Since I don't know enough bash to use 2 different systems, we have 2 options.
1. Do mapping generation by hand
2. Port MinecraftMappings to java

**Comment by Techcable** [comment]
I added 1.8 mappings using method #1. (by hand)

I think we will do it by hand until I port it to java because it is very painful to do by hand.

**Comment by wgaylord** [comment]
You can use SS to map the mc jar with the two mapping files (cl and methods) then from there compare it to the normal mc jar to get the cb/spigot mappings.

**Comment by Techcable** [comment]
@chibill 
I'm actually writing a script to do it right now :)

**Comment by wgaylord** [comment]
:) (Now if MCP would do the small update to 1.8.3)

**Comment by Techcable** [comment]
@chibill 
You know, its just the joined.srg file I really need
