### ISSUE TITLE
PaperSpigot Support

### ISSUE THREAD

**Issue by ghost** [ProjectTestificate/MinecraftMappings#3]
At the Moment this has not PaperSpigot Support
If there is already PaperSpigot Support, could someone explain it
If not will it be soon added?

**Comment by Techcable** [comment]
How would we add 'paperspigot support'?

**Comment by ghost** [comment]
At the moment you have in the files
Spigot
MCP
OBF ?
SRG ?

I thought there is no paperspigot support or can i just use the Spigot files

**Comment by Techcable** [comment]
Spigot mappings are the same as paper mappings

**Comment by ghost** [comment]
Thanks
