### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Zone-Infinity** [ProjectTestificate/MinecraftMappings#5]
Hi, I don't really know how to use these ??
Can you send me a guide or something.

**Comment by Techcable** [comment]
How to use this depends on what you want to do.

This is the mappings format used in [SpecialSource](https://github.com/md-5/SpecialSource/) and I believe spigot BuildTools.

If you know what you are doing navigating these mappings shouldn't be too hard (and unfortunately I don't have time to write a tutorial). I would look into Specialsource & Spigot BuildTools for inspiration.
